version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      USER_UID: 1001
      USER_GID: 1001
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: psql:5432
      GITEA__database__NAME: giteadb
      GITEA__database__USER: gitea
      GITEA__database__PASSWD_FILE: /run/secrets/gitea-password
      VIRTUAL_HOST: "git.jomer.dev"
      LETSENCRYPT_HOST: "git.jomer.dev"
      NETWORK_ACCESS: internal
      HTTP_PORT: 80
    restart: unless-stopped
    # depends_on:
      # - psql
    networks:
      - gitea_frontend
      - psql_backend
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    #ports:
    #  - "22:22"
    secrets:
      - gitea-password 
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.rule: Host(`git.jomer.dev`)
      traefik.http.routers.gitea.entrypoints: websecure
      traefik.http.routers.gitea.tls.certresolver: letsencrypt
      traefik.http.routers.gitea.middlewares: internal-network
      traefik.http.services.gitea.loadbalancer.server.port: 80
      traefik.docker.network: gitea_frontend

networks:
    psql_backend:
        external: true
    gitea_frontend:
        name: gitea_frontend

secrets:
    gitea-password:
        file: ../.secrets/gitea/password
        name: gitea-password