version: '3.7'

services:
  wordpress:
    image: wordpress:6-apache
    expose:
      - 80
    restart: unless-stopped
    networks:
      - ig_193_frontend
      - mariadb_backend
    environment:
      WORDPRESS_DB_HOST: "mariadb"
      WORDPRESS_DB_USER: "ig_193_db_user"
      WORDPRESS_DB_PASSWORD: "IG193WordpressBatteryStaple"
      WORDPRESS_DB_NAME: "ig_193_db"
      WORDPRESS_AUTH_KEY: "k3,9V#k0Nlk&==a[dAj3i<*l23H*42F!<Yp9~6+{/nmwQqVPB6N?CM$$;]?<W8~C_"
      WORDPRESS_SECURE_AUTH_KEY: "/*&!c6qh3`0`1+A[0tiI)!voIjh}O<Kf|e{o9XDbLwOY9,d`mFsn&#[C^siJ*U@8"
      WORDPRESS_LOGGED_IN_KEY: "$$eg:KPMd,Bw9^A4gySXqXgEdAoNJB0}uPOBz@?PDu!sDNf}vjSudX^LpC/lJ3WrT"
      WORDPRESS_NONCE_KEY: "rZO@sKpfuhL+PX=xlm ApcyFX<n9Q=:7>)3y}&(1GrB8%K}ryP]gO{7w8<JSwbIt"
      WORDPRESS_AUTH_SALT: "GbRNwh.:du#.sZHGS1uA^~;h4z2w9*pGUBv3U?p_$$htg(xA&(6>>dQutCM]$$hs0,"
      WORDPRESS_SECURE_AUTH_SALT: "O6*_[BK~h&Mv/~%fj|ki?rHeKRcvoTCx2!W4:^FRq$$Vy;G)E[TVT`|G/~6F~! WM"
      WORDPRESS_LOGGED_IN_SALT: "2+dYx.BEg/QU7>r!4n#,DH6>=H_Ic?C#,EMf%ry:sT^G`#lzP.[fHiGSSqhSo+-}"
      WORDPRESS_NONCE_SALT: "3@I@vTU;nrlR1GMI5xy!9Z!FAW^G{lm$$W`X%k^#fZKsf/`>KtD[$$/7{4hoY x)3U"
    volumes:
      - ./wordpress:/var/www/html
    # depends_on:
      # - mariadb
    labels:
      traefik.enable: true
      traefik.http.routers.ig-193.rule: Host(`ig-193.de`)
      traefik.http.routers.ig-193.entrypoints: websecure
      traefik.http.routers.ig-193.tls.certresolver: letsencrypt
      traefik.docker.network: ig_193_frontend

networks:
  ig_193_frontend:
    name: ig_193_frontend
  mariadb_backend:
    external: true