version: '3.1'

services:
    mariadb:
        container_name: mariadb
        hostname: mariadb
        image: mariadb:10.8
        restart: always
        volumes:
            - ./conf:/etc/mysql/conf.d
            - ./data:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-password
            MARIADB_AUTO_UPGRADE: true
        networks:
            - backend
        secrets:
            - mariadb-password

networks:
    backend:

secrets:
    mariadb-password:
        file: ../.secrets/mariadb/password
        name: mariadb-password